{
 "title": "Disk Usage & Folder Scan Dashboard",
 "tags": [
  "usage",
  "volume",
  "disk",
  "folder",
  "du"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "folder",
    "label": "Subfolder",
    "query": {
     "query": "label_values(du_folder_size_bytes{depth=\"1\"},folder)"
    }
   },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Subfolder Size Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  du_folder_size_bytes{parent_path=~\"(/)?$folder$\", folder!~\"@.*\"}  # 전체폴더\r\n)",
     "legendFormat": "{{folder}}"
    }
   ]
  },
  {
   "title": "Disk Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "du_disk_total_bytes {instance=\"$instance\"}",
     "legendFormat": "disk total bytes"
    },
    {
     "expr": "du_disk_used_bytes {instance=\"$instance\"}",
     "legendFormat": "disk used bytes"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "du_disk_used_percent {instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "du_disk_free_percent{instance=\"$instance\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Folder Scan Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(du_scan_duration_seconds_sum[5m]) / rate(du_scan_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "# Scans / hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(du_scan_total{instance=\"$instance\"}[1h])"
    }
   ]
  },
  {
   "title": "Scan Errors (Total)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "du_scan_errors_total {instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Subfolder File Counts (Historical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "du_subfolder_file_count{parent_path=~\"(/)?$folder$\",folder!~\"@.*\", instance=\"$instance\"}",
     "legendFormat": "{{folder}}"
    }
   ]
  },
  {
   "title": "Subfolder Total Size (Historical)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "du_subfolder_total_size_bytes{folder!~\"@.*\", instance=\"$instance\"}",
     "legendFormat": "{{folder}}"
    }
   ]
  },
  {
   "title": "Newest mtime in subfolder",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "du_subfolder_newest_mtime_seconds{instance=\"$instance\", parent_path=~\"(/)?$folder$\",folder!~\"@.*\"} * 1000",
     "legendFormat": "{{folder}}"
    }
   ]
  },
  {
   "title": "Oldest mtime in subfolder",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "du_subfolder_oldest_mtime_seconds{instance=\"$instance\", parent_path=~\"(/)?$folder$\",folder!~\"@.*\"} * 1000",
     "legendFormat": "{{folder}}"
    }
   ]
  }
 ]
}